# Generated by Django 5.1.1 on 2024-10-17 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProphesiedEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('date', models.IntegerField()),
                ('trend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yhat_lower', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yhat_upper', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trend_lower', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trend_upper', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additive_terms', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additive_terms_lower', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additive_terms_upper', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekly_lower', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekly_upper', models.DecimalField(decimal_places=2, max_digits=10)),
                ('multiplicative_terms', models.DecimalField(decimal_places=2, max_digits=10)),
                ('multiplicative_terms_lower', models.DecimalField(decimal_places=2, max_digits=10)),
                ('multiplicative_terms_upper', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yhat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.IntegerField()),
                ('updated', models.IntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.stockentity')),
            ],
            options={
                'db_table': 'prophesied',
            },
        ),
    ]
